# Generated by Django 4.2.17 on 2024-12-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='game',
            name='age_limited',
        ),
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
